# Generated by Django 4.0 on 2021-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('резерв', 'Резерв'), ('оплачена', 'Оплачена'), ('проведена', 'Проведена'), ('отменена', 'Отменена')], max_length=20)),
            ],
        ),
    ]
